---
- name: Копирование файлов на сервер
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - { src: "example.txt", dest: "/tmp/example.txt", owner: "root", group: "root", mode: "0644" }
...
